/*
* NombreProgra.asm
*
* Creado: 15/02/25
* Autor : José_alfaro
* Descripción: Pre_lab_3
*/
/****************************************/
// Encabezado (Definición de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START
//variable_name:     .byte   1   // Memory alocation for variable_name:     .byte   (byte size)

.cseg
.org 0x0000
	JMP START
.org PCI1addr
	JMP PIN_CHANGE_C
.org OVF0addr
	JMP ISR_TMER0_NORMAL
 /****************************************/
 START:
// Configuración de la pila
LDI     R16, LOW(RAMEND)
OUT     SPL, R16
LDI     R16, HIGH(RAMEND)
OUT     SPH, R16
/****************************************/
// Configuracion MCU
LDI R16, 0X00
STS UCSR0B, R16
SETUP:
	CLI //DESACTIVAMOS INTERRUPCIONES GLOBALES
	LDI R16, (1 << CLKPCE)//HABILITAMOS EL PRESCALADO DE EL OSCILADOR
	STS CLKPR, R16
	LDI R16, (1 << CLKPS2) //INDICAMOS EL PRESCALER 16MHz/16 = 1Mhz
	STS CLKPR, R16

	//CONFIGURAMOS SALIDAS 
	//CONFIGURACIÓN DE EL CONTADOR DE LEDS
	SBI DDRC, DDC0
    SBI DDRC, DDC1
	SBI DDRC, DDC2
	SBI DDRC, DDC3
	CBI PORTC, PORTC0
	CBI PORTC, PORTC1
	CBI PORTC, PORTC2
	CBI PORTC, PORTC3

	//CONFIGURAMOS LAS ENTRADAS CON PULL UP
	CBI DDRC, DDC4
	CBI DDRC, DDC5
	SBI PORTC, PORTC4
	SBI PORTC, PORTC5

	//DEFININOMOS NUESTRAS SALIDAS Y MOSTRAMOS EL VALOR DE 0 EN EL DISPLAY
	// DISPLAY
	SBI DDRD, DDD0
	SBI PORTD, PORTD0
	SBI DDRD, DDD1
	CBI PORTD, PORTD1
	SBI DDRD, DDD2
	CBI PORTD, PORTD2
	SBI DDRD, DDD3
	CBI PORTD, PORTD3
	SBI DDRD, DDD4
	CBI PORTD, PORTD4
	SBI DDRD, DDD5
	CBI PORTD, PORTD5
	SBI DDRD, DDD6
	CBI PORTD, PORTD6
	SBI DDRD, DDD7
	SBI PORTD, PORTD7

	//SALIDAS QUE NOS AYUDARAN PARA LOS DISPLAYS
	SBI DDRB, DDB0
	SBI DDRB, DDB1
	CBI PORTB, PORTB0
	CBI PORTB, PORTB1

	//CONFIGURAMOS LA INTERRUPCIÓN DE EL TIMER0 EN MODO NORMAL
	LDI R16, 0X00
	OUT TCCR0A, R16 //MODO NORMAL (N -> OVERFLOW)
	LDI R16, (1 << CS00)|(1 << CS01)
	OUT TCCR0B, R16 //PRESCALER DE 64
	LDI R16, 100 //COLOCAMOS EL VALOR INICIAL EN LA INTERRUPCIÓN 
	OUT TCNT0, R16
	LDI R16, (1 << TOIE0) //HABILITAMOS LA INTERRUPCIÓN POR OVERFLOW
	STS TIMSK0, R16
	LDI R16, (1 << TOV0) // HABILITAMOS LA FLAG POR OVERFLOW
	OUT TIFR0, R16

	//CONFIGURAMOS LA INTERRUPCIÓN DE PIN CHANGE EN EL PUERTO C
	LDI R16, (1 << PCIE1) //HABILITAMOS PIN CHANGE EN EL PUERTO C
	STS PCICR, R16

	LDI R16, (1 << PCINT12)|(1 << PCINT13) //HABILITAMOS LA INTERRUPCIÓN A LOS BITS 4 Y 5
	STS PCMSK1, R16

	SEI //HABILITAMOS INTERRUPCIONES GLOBALES

	LDI ZH, HIGH(disp7seg<<1) //COLOCAMOS Z EN LA POSICIÓN 0 DE NUESTRA TABLA
	LDI ZL, LOW(disp7seg<<1)

	CLR R1
	CLR R17
	CLR R19
	CLR R20
	CLR R21
	CLR R22
	CLR R23
	CLR R26

	IN R18, PINC //ESTO NOS AYUDA A VERIFICAR QUE HAYA SUMA SOLO EN EL FLANCO DE BAJADA
/****************************************/
// Loop Infinito
MAIN_LOOP:
    IN  R16, PORTC
    ANDI R16, 0xF0	//MÁSCARA PARA DEJAS SOLO EL NIBBLE MÁS SIGNIFICATIVO DONDE ESTAN LOS BOTONES
    MOV R19, R17 //AQUÍ COPIAMOS EL VALOR DEL CONTADOR 
    ANDI R19, 0x0F //MÁSCARA PARA DEAJAR EL CONTADOR DE 4 BITS
    OR  R16, R19 //COMBINAMOS EL VALOR DEL CONTADOR CON EL DE LAS ENTRADAS
    OUT PORTC, R16


	LDI ZH, HIGH(disp7seg<<1) //COLOCAMOS Z EN LA POSICIÓN 0 DE NUESTRA TABLA
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R23 //LE SUMAMOS LA POSICIÓN A Z
	ADC ZH, R1 //R1 ESTA VACÍO ASÍ QUE ZH SIEMPRE VA A SER 0
	LPM R24, Z
	CBI PORTB, PORTB1
	SBI PORTB, PORTB0
	OUT PORTD, R24

	LDI ZH, HIGH(disp7seg<<1) //COLOCAMOS Z EN LA POSICIÓN 0 DE NUESTRA TABLA
	LDI ZL, LOW(disp7seg<<1)
	ADD ZL, R26 //LE SUMAMOS LA POSICIÓN A Z
	ADC ZH, R1 //R1 ESTA VACÍO ASÍ QUE ZH SIEMPRE VA A SER 0
	LPM R24, Z
	CBI PORTB, PORTB0
	SBI PORTB, PORTB1
	OUT PORTD, R24


    RJMP MAIN_LOOP

/****************************************/
// NON-Interrupt subroutines

/****************************************/
// Interrupt routines
PIN_CHANGE_C:
	IN  R19, PINC //LEEMOS EL VALOR ACTUAL DESPUÉS EJECUTAR LA INTERRUPCIÓN
    MOV R20, R19 
    EOR R20, R18  // OR ENTRE VALOR ACUTAL Y PASADO DE LOS BOTONES, DETERMINANDO SI CAMBIARON
    SBRS R20, 4  //SE SALTA LA SIGUIENTE LINEA SI NO HUBO CAMBIO EN EL BOTON DE AUMENTO
    RJMP DECREASE
	//ESTO ES PARA DETERMINAR SI EL CAMBIO FUE EN EL FLANCO DE BAJADA
    SBRC R19, 4 //SI ES 0 EL BIT 4 ES PORQUE SÍ FUE FLANCO DE BAJADA
    RJMP DECREASE
    INC R17

DECREASE:
    //EN R20 ES EL REGISTRO DONDE SABEMOS QUÉ VALOR CAMBIÓ
    SBRS R20, 5 //SI ES 1 SE SABE QUE SI HUBO CAMBIO
    RJMP ACTUALIZACION

    //ESTO ES PARA DETERMINAR SI EL CAMBIO FUE EN EL FLANCO DE BAJADA
    SBRC R19, 5
    RJMP ACTUALIZACION
    DEC R17

// AQUÍ COLOCAMOS EL NUEVO VALOR ANTIGUO PARA LA SIGUIENTE INTERRUPCIÓN
ACTUALIZACION:
    MOV R18, R19
    RETI

ISR_TMER0_NORMAL:
	LDI R25, 100
	OUT TCNT0, R25
	PUSH R22
	INC R21
	CPI R21, 100
	IN R22, SREG
	SBRS R22, 0b00000010
	RJMP ONE_SEG
	POP R22
	RETI 

ONE_SEG:
	CLR R21
	INC R23
	CPI R23, 10
	BREQ DECENA
	POP R22
	RETI

DECENA:
	CLR R23
	INC R26
	CPI R26, 6
	BREQ RESET
	POP R22
	RETI

RESET:
	CLR R26
	POP R22
	RETI

/****************************************/
disp7seg:
	.db 0x81, 0xCF, 0x92, 0x86, 0xCC, 0xA4, 0xA0, 0x8F, 0x80, 0x84, 0x88, 0xE0, 0xB1, 0xC2, 0xB0, 0xB8